// source: google/devtools/containeranalysis/v1alpha1/bill_of_materials.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb = require('../../../../google/devtools/containeranalysis/v1alpha1/package_vulnerability_pb.js');
goog.object.extend(proto, google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb);
goog.exportSymbol('proto.google.devtools.containeranalysis.v1alpha1.PackageManager', null, global);
goog.exportSymbol('proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture', null, global);
goog.exportSymbol('proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution', null, global);
goog.exportSymbol('proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation', null, global);
goog.exportSymbol('proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location', null, global);
goog.exportSymbol('proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.devtools.containeranalysis.v1alpha1.PackageManager, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.displayName = 'proto.google.devtools.containeranalysis.v1alpha1.PackageManager';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.displayName = 'proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.displayName = 'proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.repeatedFields_, null);
};
goog.inherits(proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.displayName = 'proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.repeatedFields_, null);
};
goog.inherits(proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.displayName = 'proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.prototype.toObject = function(opt_includeInstance) {
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.devtools.containeranalysis.v1alpha1.PackageManager;
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture = {
  ARCHITECTURE_UNSPECIFIED: 0,
  X86: 1,
  X64: 2
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.toObject = function(opt_includeInstance) {
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.toObject = function(includeInstance, msg) {
  var f, obj = {
    cpeUri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    architecture: jspb.Message.getFieldWithDefault(msg, 2, 0),
    latestVersion: (f = msg.getLatestVersion()) && google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version.toObject(includeInstance, f),
    maintainer: jspb.Message.getFieldWithDefault(msg, 4, ""),
    url: jspb.Message.getFieldWithDefault(msg, 6, ""),
    description: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution;
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpeUri(value);
      break;
    case 2:
      var value = /** @type {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture} */ (reader.readEnum());
      msg.setArchitecture(value);
      break;
    case 3:
      var value = new google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version;
      reader.readMessage(value,google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version.deserializeBinaryFromReader);
      msg.setLatestVersion(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaintainer(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCpeUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getArchitecture();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getLatestVersion();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version.serializeBinaryToWriter
    );
  }
  f = message.getMaintainer();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string cpe_uri = 1;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.getCpeUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.setCpeUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Architecture architecture = 2;
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.getArchitecture = function() {
  return /** @type {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Architecture} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.setArchitecture = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional VulnerabilityType.Version latest_version = 3;
 * @return {?proto.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.getLatestVersion = function() {
  return /** @type{?proto.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version} */ (
    jspb.Message.getWrapperField(this, google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version, 3));
};


/**
 * @param {?proto.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version|undefined} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} returns this
*/
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.setLatestVersion = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.clearLatestVersion = function() {
  return this.setLatestVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.hasLatestVersion = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string maintainer = 4;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.getMaintainer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.setMaintainer = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string url = 6;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string description = 7;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.toObject = function(opt_includeInstance) {
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.toObject = function(includeInstance, msg) {
  var f, obj = {
    cpeUri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: (f = msg.getVersion()) && google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version.toObject(includeInstance, f),
    path: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location;
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpeUri(value);
      break;
    case 2:
      var value = new google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version;
      reader.readMessage(value,google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version.deserializeBinaryFromReader);
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCpeUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version.serializeBinaryToWriter
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string cpe_uri = 1;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.getCpeUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.setCpeUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional VulnerabilityType.Version version = 2;
 * @return {?proto.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.getVersion = function() {
  return /** @type{?proto.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version} */ (
    jspb.Message.getWrapperField(this, google_devtools_containeranalysis_v1alpha1_package_vulnerability_pb.VulnerabilityType.Version, 2));
};


/**
 * @param {?proto.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.Version|undefined} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location} returns this
*/
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.setVersion = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.clearVersion = function() {
  return this.setVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.hasVersion = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.repeatedFields_ = [10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.toObject = function(opt_includeInstance) {
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    distributionList: jspb.Message.toObjectList(msg.getDistributionList(),
    proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package;
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 10:
      var value = new proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution;
      reader.readMessage(value,proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.deserializeBinaryFromReader);
      msg.addDistribution(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDistributionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Distribution distribution = 10;
 * @return {!Array<!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution>}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.getDistributionList = function() {
  return /** @type{!Array<!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution, 10));
};


/**
 * @param {!Array<!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution>} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package} returns this
*/
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.setDistributionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.addDistribution = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Distribution, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Package.prototype.clearDistributionList = function() {
  return this.setDistributionList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.toObject = function(opt_includeInstance) {
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    locationList: jspb.Message.toObjectList(msg.getLocationList(),
    proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation;
  return proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location;
      reader.readMessage(value,proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.deserializeBinaryFromReader);
      msg.addLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Location location = 2;
 * @return {!Array<!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location>}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.getLocationList = function() {
  return /** @type{!Array<!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location, 2));
};


/**
 * @param {!Array<!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location>} value
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation} returns this
*/
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.setLocationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location}
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.addLocation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Location, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation} returns this
 */
proto.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation.prototype.clearLocationList = function() {
  return this.setLocationList([]);
};


goog.object.extend(exports, proto.google.devtools.containeranalysis.v1alpha1);
