// source: google/cloud/automl/v1beta1/model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_cloud_automl_v1beta1_image_pb = require('../../../../google/cloud/automl/v1beta1/image_pb.js');
goog.object.extend(proto, google_cloud_automl_v1beta1_image_pb);
var google_cloud_automl_v1beta1_text_pb = require('../../../../google/cloud/automl/v1beta1/text_pb.js');
goog.object.extend(proto, google_cloud_automl_v1beta1_text_pb);
var google_cloud_automl_v1beta1_translation_pb = require('../../../../google/cloud/automl/v1beta1/translation_pb.js');
goog.object.extend(proto, google_cloud_automl_v1beta1_translation_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.cloud.automl.v1beta1.Model', null, global);
goog.exportSymbol('proto.google.cloud.automl.v1beta1.Model.DeploymentState', null, global);
goog.exportSymbol('proto.google.cloud.automl.v1beta1.Model.ModelMetadataCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.automl.v1beta1.Model = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.cloud.automl.v1beta1.Model.oneofGroups_);
};
goog.inherits(proto.google.cloud.automl.v1beta1.Model, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.automl.v1beta1.Model.displayName = 'proto.google.cloud.automl.v1beta1.Model';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.cloud.automl.v1beta1.Model.oneofGroups_ = [[13,14,15]];

/**
 * @enum {number}
 */
proto.google.cloud.automl.v1beta1.Model.ModelMetadataCase = {
  MODEL_METADATA_NOT_SET: 0,
  IMAGE_CLASSIFICATION_MODEL_METADATA: 13,
  TEXT_CLASSIFICATION_MODEL_METADATA: 14,
  TRANSLATION_MODEL_METADATA: 15
};

/**
 * @return {proto.google.cloud.automl.v1beta1.Model.ModelMetadataCase}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getModelMetadataCase = function() {
  return /** @type {proto.google.cloud.automl.v1beta1.Model.ModelMetadataCase} */(jspb.Message.computeOneofCase(this, proto.google.cloud.automl.v1beta1.Model.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.automl.v1beta1.Model.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.automl.v1beta1.Model} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.automl.v1beta1.Model.toObject = function(includeInstance, msg) {
  var f, obj = {
    imageClassificationModelMetadata: (f = msg.getImageClassificationModelMetadata()) && google_cloud_automl_v1beta1_image_pb.ImageClassificationModelMetadata.toObject(includeInstance, f),
    textClassificationModelMetadata: (f = msg.getTextClassificationModelMetadata()) && google_cloud_automl_v1beta1_text_pb.TextClassificationModelMetadata.toObject(includeInstance, f),
    translationModelMetadata: (f = msg.getTranslationModelMetadata()) && google_cloud_automl_v1beta1_translation_pb.TranslationModelMetadata.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    displayName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    datasetId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateTime: (f = msg.getUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deploymentState: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.automl.v1beta1.Model}
 */
proto.google.cloud.automl.v1beta1.Model.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.automl.v1beta1.Model;
  return proto.google.cloud.automl.v1beta1.Model.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.automl.v1beta1.Model} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.automl.v1beta1.Model}
 */
proto.google.cloud.automl.v1beta1.Model.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 13:
      var value = new google_cloud_automl_v1beta1_image_pb.ImageClassificationModelMetadata;
      reader.readMessage(value,google_cloud_automl_v1beta1_image_pb.ImageClassificationModelMetadata.deserializeBinaryFromReader);
      msg.setImageClassificationModelMetadata(value);
      break;
    case 14:
      var value = new google_cloud_automl_v1beta1_text_pb.TextClassificationModelMetadata;
      reader.readMessage(value,google_cloud_automl_v1beta1_text_pb.TextClassificationModelMetadata.deserializeBinaryFromReader);
      msg.setTextClassificationModelMetadata(value);
      break;
    case 15:
      var value = new google_cloud_automl_v1beta1_translation_pb.TranslationModelMetadata;
      reader.readMessage(value,google_cloud_automl_v1beta1_translation_pb.TranslationModelMetadata.deserializeBinaryFromReader);
      msg.setTranslationModelMetadata(value);
      break;
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatasetId(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateTime(value);
      break;
    case 8:
      var value = /** @type {!proto.google.cloud.automl.v1beta1.Model.DeploymentState} */ (reader.readEnum());
      msg.setDeploymentState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.automl.v1beta1.Model.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.automl.v1beta1.Model} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.automl.v1beta1.Model.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImageClassificationModelMetadata();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_cloud_automl_v1beta1_image_pb.ImageClassificationModelMetadata.serializeBinaryToWriter
    );
  }
  f = message.getTextClassificationModelMetadata();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      google_cloud_automl_v1beta1_text_pb.TextClassificationModelMetadata.serializeBinaryToWriter
    );
  }
  f = message.getTranslationModelMetadata();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_cloud_automl_v1beta1_translation_pb.TranslationModelMetadata.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDatasetId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateTime();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeploymentState();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.automl.v1beta1.Model.DeploymentState = {
  DEPLOYMENT_STATE_UNSPECIFIED: 0,
  DEPLOYED: 1,
  UNDEPLOYED: 2
};

/**
 * optional ImageClassificationModelMetadata image_classification_model_metadata = 13;
 * @return {?proto.google.cloud.automl.v1beta1.ImageClassificationModelMetadata}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getImageClassificationModelMetadata = function() {
  return /** @type{?proto.google.cloud.automl.v1beta1.ImageClassificationModelMetadata} */ (
    jspb.Message.getWrapperField(this, google_cloud_automl_v1beta1_image_pb.ImageClassificationModelMetadata, 13));
};


/**
 * @param {?proto.google.cloud.automl.v1beta1.ImageClassificationModelMetadata|undefined} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
*/
proto.google.cloud.automl.v1beta1.Model.prototype.setImageClassificationModelMetadata = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.google.cloud.automl.v1beta1.Model.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.clearImageClassificationModelMetadata = function() {
  return this.setImageClassificationModelMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.hasImageClassificationModelMetadata = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional TextClassificationModelMetadata text_classification_model_metadata = 14;
 * @return {?proto.google.cloud.automl.v1beta1.TextClassificationModelMetadata}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getTextClassificationModelMetadata = function() {
  return /** @type{?proto.google.cloud.automl.v1beta1.TextClassificationModelMetadata} */ (
    jspb.Message.getWrapperField(this, google_cloud_automl_v1beta1_text_pb.TextClassificationModelMetadata, 14));
};


/**
 * @param {?proto.google.cloud.automl.v1beta1.TextClassificationModelMetadata|undefined} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
*/
proto.google.cloud.automl.v1beta1.Model.prototype.setTextClassificationModelMetadata = function(value) {
  return jspb.Message.setOneofWrapperField(this, 14, proto.google.cloud.automl.v1beta1.Model.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.clearTextClassificationModelMetadata = function() {
  return this.setTextClassificationModelMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.hasTextClassificationModelMetadata = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional TranslationModelMetadata translation_model_metadata = 15;
 * @return {?proto.google.cloud.automl.v1beta1.TranslationModelMetadata}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getTranslationModelMetadata = function() {
  return /** @type{?proto.google.cloud.automl.v1beta1.TranslationModelMetadata} */ (
    jspb.Message.getWrapperField(this, google_cloud_automl_v1beta1_translation_pb.TranslationModelMetadata, 15));
};


/**
 * @param {?proto.google.cloud.automl.v1beta1.TranslationModelMetadata|undefined} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
*/
proto.google.cloud.automl.v1beta1.Model.prototype.setTranslationModelMetadata = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.google.cloud.automl.v1beta1.Model.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.clearTranslationModelMetadata = function() {
  return this.setTranslationModelMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.hasTranslationModelMetadata = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string display_name = 2;
 * @return {string}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.setDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string dataset_id = 3;
 * @return {string}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getDatasetId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.setDatasetId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
*/
proto.google.cloud.automl.v1beta1.Model.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp update_time = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
*/
proto.google.cloud.automl.v1beta1.Model.prototype.setUpdateTime = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.clearUpdateTime = function() {
  return this.setUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.hasUpdateTime = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional DeploymentState deployment_state = 8;
 * @return {!proto.google.cloud.automl.v1beta1.Model.DeploymentState}
 */
proto.google.cloud.automl.v1beta1.Model.prototype.getDeploymentState = function() {
  return /** @type {!proto.google.cloud.automl.v1beta1.Model.DeploymentState} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.google.cloud.automl.v1beta1.Model.DeploymentState} value
 * @return {!proto.google.cloud.automl.v1beta1.Model} returns this
 */
proto.google.cloud.automl.v1beta1.Model.prototype.setDeploymentState = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


goog.object.extend(exports, proto.google.cloud.automl.v1beta1);
