// source: google/cloud/dialogflow/v2/agent.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_longrunning_operations_pb = require('../../../../google/longrunning/operations_pb.js');
goog.object.extend(proto, google_longrunning_operations_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js');
goog.object.extend(proto, google_protobuf_field_mask_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.Agent', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.Agent.MatchMode', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.ExportAgentRequest', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.ExportAgentResponse', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.ExportAgentResponse.AgentCase', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.GetAgentRequest', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.ImportAgentRequest', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.ImportAgentRequest.AgentCase', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.RestoreAgentRequest', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.RestoreAgentRequest.AgentCase', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.SearchAgentsRequest', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.SearchAgentsResponse', null, global);
goog.exportSymbol('proto.google.cloud.dialogflow.v2.TrainAgentRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.Agent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.dialogflow.v2.Agent.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.dialogflow.v2.Agent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.Agent.displayName = 'proto.google.cloud.dialogflow.v2.Agent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.dialogflow.v2.GetAgentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.GetAgentRequest.displayName = 'proto.google.cloud.dialogflow.v2.GetAgentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.dialogflow.v2.SearchAgentsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.SearchAgentsRequest.displayName = 'proto.google.cloud.dialogflow.v2.SearchAgentsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.dialogflow.v2.SearchAgentsResponse.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.dialogflow.v2.SearchAgentsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.SearchAgentsResponse.displayName = 'proto.google.cloud.dialogflow.v2.SearchAgentsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.dialogflow.v2.TrainAgentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.TrainAgentRequest.displayName = 'proto.google.cloud.dialogflow.v2.TrainAgentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.dialogflow.v2.ExportAgentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.ExportAgentRequest.displayName = 'proto.google.cloud.dialogflow.v2.ExportAgentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.cloud.dialogflow.v2.ExportAgentResponse.oneofGroups_);
};
goog.inherits(proto.google.cloud.dialogflow.v2.ExportAgentResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.ExportAgentResponse.displayName = 'proto.google.cloud.dialogflow.v2.ExportAgentResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.cloud.dialogflow.v2.ImportAgentRequest.oneofGroups_);
};
goog.inherits(proto.google.cloud.dialogflow.v2.ImportAgentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.ImportAgentRequest.displayName = 'proto.google.cloud.dialogflow.v2.ImportAgentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.cloud.dialogflow.v2.RestoreAgentRequest.oneofGroups_);
};
goog.inherits(proto.google.cloud.dialogflow.v2.RestoreAgentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.dialogflow.v2.RestoreAgentRequest.displayName = 'proto.google.cloud.dialogflow.v2.RestoreAgentRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.dialogflow.v2.Agent.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.Agent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.Agent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.Agent.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    displayName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    defaultLanguageCode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    supportedLanguageCodesList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    timeZone: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    avatarUri: jspb.Message.getFieldWithDefault(msg, 7, ""),
    enableLogging: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    matchMode: jspb.Message.getFieldWithDefault(msg, 9, 0),
    classificationThreshold: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.Agent}
 */
proto.google.cloud.dialogflow.v2.Agent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.Agent;
  return proto.google.cloud.dialogflow.v2.Agent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.Agent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.Agent}
 */
proto.google.cloud.dialogflow.v2.Agent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDefaultLanguageCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addSupportedLanguageCodes(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimeZone(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarUri(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableLogging(value);
      break;
    case 9:
      var value = /** @type {!proto.google.cloud.dialogflow.v2.Agent.MatchMode} */ (reader.readEnum());
      msg.setMatchMode(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setClassificationThreshold(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.Agent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.Agent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.Agent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDefaultLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSupportedLanguageCodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getTimeZone();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAvatarUri();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEnableLogging();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getMatchMode();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getClassificationThreshold();
  if (f !== 0.0) {
    writer.writeFloat(
      10,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.dialogflow.v2.Agent.MatchMode = {
  MATCH_MODE_UNSPECIFIED: 0,
  MATCH_MODE_HYBRID: 1,
  MATCH_MODE_ML_ONLY: 2
};

/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string display_name = 2;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string default_language_code = 3;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getDefaultLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setDefaultLanguageCode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated string supported_language_codes = 4;
 * @return {!Array<string>}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getSupportedLanguageCodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setSupportedLanguageCodesList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.addSupportedLanguageCodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.clearSupportedLanguageCodesList = function() {
  return this.setSupportedLanguageCodesList([]);
};


/**
 * optional string time_zone = 5;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getTimeZone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setTimeZone = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string avatar_uri = 7;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getAvatarUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setAvatarUri = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool enable_logging = 8;
 * @return {boolean}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getEnableLogging = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setEnableLogging = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional MatchMode match_mode = 9;
 * @return {!proto.google.cloud.dialogflow.v2.Agent.MatchMode}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getMatchMode = function() {
  return /** @type {!proto.google.cloud.dialogflow.v2.Agent.MatchMode} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.google.cloud.dialogflow.v2.Agent.MatchMode} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setMatchMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional float classification_threshold = 10;
 * @return {number}
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.getClassificationThreshold = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.dialogflow.v2.Agent} returns this
 */
proto.google.cloud.dialogflow.v2.Agent.prototype.setClassificationThreshold = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.GetAgentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.GetAgentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.GetAgentRequest}
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.GetAgentRequest;
  return proto.google.cloud.dialogflow.v2.GetAgentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.GetAgentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.GetAgentRequest}
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.GetAgentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.GetAgentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.GetAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.GetAgentRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.SearchAgentsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pageSize: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageToken: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.SearchAgentsRequest;
  return proto.google.cloud.dialogflow.v2.SearchAgentsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.SearchAgentsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPageToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest} returns this
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 page_size = 2;
 * @return {number}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest} returns this
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string page_token = 3;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.getPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsRequest} returns this
 */
proto.google.cloud.dialogflow.v2.SearchAgentsRequest.prototype.setPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.SearchAgentsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    agentsList: jspb.Message.toObjectList(msg.getAgentsList(),
    proto.google.cloud.dialogflow.v2.Agent.toObject, includeInstance),
    nextPageToken: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.SearchAgentsResponse;
  return proto.google.cloud.dialogflow.v2.SearchAgentsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.dialogflow.v2.Agent;
      reader.readMessage(value,proto.google.cloud.dialogflow.v2.Agent.deserializeBinaryFromReader);
      msg.addAgents(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextPageToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.SearchAgentsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAgentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.cloud.dialogflow.v2.Agent.serializeBinaryToWriter
    );
  }
  f = message.getNextPageToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated Agent agents = 1;
 * @return {!Array<!proto.google.cloud.dialogflow.v2.Agent>}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.getAgentsList = function() {
  return /** @type{!Array<!proto.google.cloud.dialogflow.v2.Agent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.dialogflow.v2.Agent, 1));
};


/**
 * @param {!Array<!proto.google.cloud.dialogflow.v2.Agent>} value
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse} returns this
*/
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.setAgentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.dialogflow.v2.Agent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.dialogflow.v2.Agent}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.addAgents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.dialogflow.v2.Agent, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse} returns this
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.clearAgentsList = function() {
  return this.setAgentsList([]);
};


/**
 * optional string next_page_token = 2;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.getNextPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.SearchAgentsResponse} returns this
 */
proto.google.cloud.dialogflow.v2.SearchAgentsResponse.prototype.setNextPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.TrainAgentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.TrainAgentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.TrainAgentRequest}
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.TrainAgentRequest;
  return proto.google.cloud.dialogflow.v2.TrainAgentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.TrainAgentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.TrainAgentRequest}
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.TrainAgentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.TrainAgentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.TrainAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.TrainAgentRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.ExportAgentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.ExportAgentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    agentUri: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentRequest}
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.ExportAgentRequest;
  return proto.google.cloud.dialogflow.v2.ExportAgentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.ExportAgentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentRequest}
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgentUri(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.ExportAgentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.ExportAgentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAgentUri();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string agent_uri = 2;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.prototype.getAgentUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.ExportAgentRequest.prototype.setAgentUri = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.AgentCase = {
  AGENT_NOT_SET: 0,
  AGENT_URI: 1,
  AGENT_CONTENT: 2
};

/**
 * @return {proto.google.cloud.dialogflow.v2.ExportAgentResponse.AgentCase}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.getAgentCase = function() {
  return /** @type {proto.google.cloud.dialogflow.v2.ExportAgentResponse.AgentCase} */(jspb.Message.computeOneofCase(this, proto.google.cloud.dialogflow.v2.ExportAgentResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.ExportAgentResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.ExportAgentResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    agentUri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    agentContent: msg.getAgentContent_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentResponse}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.ExportAgentResponse;
  return proto.google.cloud.dialogflow.v2.ExportAgentResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.ExportAgentResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentResponse}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgentUri(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAgentContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.ExportAgentResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.ExportAgentResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional string agent_uri = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.getAgentUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentResponse} returns this
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.setAgentUri = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.google.cloud.dialogflow.v2.ExportAgentResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentResponse} returns this
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.clearAgentUri = function() {
  return jspb.Message.setOneofField(this, 1, proto.google.cloud.dialogflow.v2.ExportAgentResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.hasAgentUri = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes agent_content = 2;
 * @return {!(string|Uint8Array)}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.getAgentContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes agent_content = 2;
 * This is a type-conversion wrapper around `getAgentContent()`
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.getAgentContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAgentContent()));
};


/**
 * optional bytes agent_content = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAgentContent()`
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.getAgentContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAgentContent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentResponse} returns this
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.setAgentContent = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.dialogflow.v2.ExportAgentResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.dialogflow.v2.ExportAgentResponse} returns this
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.clearAgentContent = function() {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.dialogflow.v2.ExportAgentResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.dialogflow.v2.ExportAgentResponse.prototype.hasAgentContent = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.AgentCase = {
  AGENT_NOT_SET: 0,
  AGENT_URI: 2,
  AGENT_CONTENT: 3
};

/**
 * @return {proto.google.cloud.dialogflow.v2.ImportAgentRequest.AgentCase}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.getAgentCase = function() {
  return /** @type {proto.google.cloud.dialogflow.v2.ImportAgentRequest.AgentCase} */(jspb.Message.computeOneofCase(this, proto.google.cloud.dialogflow.v2.ImportAgentRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.ImportAgentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    agentUri: jspb.Message.getFieldWithDefault(msg, 2, ""),
    agentContent: msg.getAgentContent_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.ImportAgentRequest}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.ImportAgentRequest;
  return proto.google.cloud.dialogflow.v2.ImportAgentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.ImportAgentRequest}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgentUri(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAgentContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.ImportAgentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string agent_uri = 2;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.getAgentUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.setAgentUri = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.dialogflow.v2.ImportAgentRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.clearAgentUri = function() {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.dialogflow.v2.ImportAgentRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.hasAgentUri = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes agent_content = 3;
 * @return {!(string|Uint8Array)}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.getAgentContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes agent_content = 3;
 * This is a type-conversion wrapper around `getAgentContent()`
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.getAgentContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAgentContent()));
};


/**
 * optional bytes agent_content = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAgentContent()`
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.getAgentContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAgentContent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.setAgentContent = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.google.cloud.dialogflow.v2.ImportAgentRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.dialogflow.v2.ImportAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.clearAgentContent = function() {
  return jspb.Message.setOneofField(this, 3, proto.google.cloud.dialogflow.v2.ImportAgentRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.dialogflow.v2.ImportAgentRequest.prototype.hasAgentContent = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.AgentCase = {
  AGENT_NOT_SET: 0,
  AGENT_URI: 2,
  AGENT_CONTENT: 3
};

/**
 * @return {proto.google.cloud.dialogflow.v2.RestoreAgentRequest.AgentCase}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.getAgentCase = function() {
  return /** @type {proto.google.cloud.dialogflow.v2.RestoreAgentRequest.AgentCase} */(jspb.Message.computeOneofCase(this, proto.google.cloud.dialogflow.v2.RestoreAgentRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.dialogflow.v2.RestoreAgentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    parent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    agentUri: jspb.Message.getFieldWithDefault(msg, 2, ""),
    agentContent: msg.getAgentContent_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.dialogflow.v2.RestoreAgentRequest;
  return proto.google.cloud.dialogflow.v2.RestoreAgentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgentUri(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAgentContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.dialogflow.v2.RestoreAgentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional string parent = 1;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string agent_uri = 2;
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.getAgentUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.setAgentUri = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.dialogflow.v2.RestoreAgentRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.clearAgentUri = function() {
  return jspb.Message.setOneofField(this, 2, proto.google.cloud.dialogflow.v2.RestoreAgentRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.hasAgentUri = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes agent_content = 3;
 * @return {!(string|Uint8Array)}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.getAgentContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes agent_content = 3;
 * This is a type-conversion wrapper around `getAgentContent()`
 * @return {string}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.getAgentContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAgentContent()));
};


/**
 * optional bytes agent_content = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAgentContent()`
 * @return {!Uint8Array}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.getAgentContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAgentContent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.setAgentContent = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.google.cloud.dialogflow.v2.RestoreAgentRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.cloud.dialogflow.v2.RestoreAgentRequest} returns this
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.clearAgentContent = function() {
  return jspb.Message.setOneofField(this, 3, proto.google.cloud.dialogflow.v2.RestoreAgentRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.dialogflow.v2.RestoreAgentRequest.prototype.hasAgentContent = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.google.cloud.dialogflow.v2);
